﻿CLEDITOR_I18N = {
    "Bold": "Bold",
    "Italic": "Italic",
    "Underline": "Underline",
    "Strikethrough": "Strikethrough",
    "Subscript": "Subscript",
    "Superscript": "Superscript",
    "Font": "Font",
    "Text size": "Text size",
    "Style": "Style",
    "Text color": "Text color",
    "Highlight color": "Highlight color",
    "Remove formatting": "Remove formatting",
    "Unordered list": "Unordered list",
    "Ordered list": "Ordered list",
    "Outdent": "Outdent",
    "Indent": "Indent",
    "Align left": "Align left",
    "Align center": "Align center",
    "Align right": "Align right",
    "Justify": "Justify",
    "Undo": "Undo",
    "Redo": "Redo",
    "Insert horizontal rule": "Insert horizontal rule",
    "Insert image": "Insert image",
    "Insert link": "Insert link",
    "Remove link": "Remove link",
    "Cut": "Cut",
    "Copy": "Copy",
    "Paste": "Paste",
    "Paste as text": "Paste as text",
    "Print": "Print",
    "Show source": "Show source"
}