CLEDITOR_I18N = {
    "Bold": "Жирный",
    "Italic": "Курсив",
    "Underline": "Подчеркнутый",
    "Strikethrough": "Перечеркнутый",
    "Subscript": "Подстрочный",
    "Superscript": "Надстрочный",
    "Font": "Шрифт",
    "Text size": "Размер шрифта",
    "Style": "Стиль",
    "Text color": "Цвет шрифта",
    "Highlight color": "Цвет подсвечивания текста",
    "Remove formatting": "Удалить форматирование",
    "Unordered list": "Маркерованный список",
    "Ordered list": "Нумерованный список",
    "Outdent": "Уменьшить отступ",
    "Indent": "Увеличить отступ",
    "Align left": "По левому краю",
    "Align center": "По центру",
    "Align right": "По правому краю",
    "Justify": "Растянуть",
    "Undo": "Отменить",
    "Redo": "Повторить",
    "Insert horizontal rule": "Вставить горизонтальную черту",
    "Insert image": "Вставить изображение",
    "Insert link": "Вставить ссылку",
    "Remove link": "Удалить ссылку",
    "Cut": "Вырезать",
    "Copy": "Копировать",
    "Paste": "Вставить",
    "Paste as text": "Вставить как текст",
    "Print": "Печать",
    "Show source": "Исходный код"
}